ShowShareButtons = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
showtoc = true
author = "WeRust"

[homeInfoParams]
Title = "WeRust 🦀"
Content = """
Welcome to WeRust, the ultimate destination for mastering the powerful and efficient Rust programming language. Our comprehensive tutorials and examples cover everything from the basics to advanced concepts, making it easy for anyone to learn and improve their skills. Whether you're a beginner looking to get started or an experienced developer looking to expand your knowledge, WeRust has everything you need to become a pro at Rust programming.
"""

[assets]
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"
site_webmanifest = "site.webmanifest"